name = "earlyadopter-api"
main = "src/index.js"
compatibility_date = "2026-07-01"

[[d1_databases]]
binding = "earlyadopter_db"
database_name = "earlyadopter-db"
database_id = "87b5f580-953d-4cf6-9001-2e787c1aadbe"
